version: '2.1'

volumes:
  rs0node1:
    driver: "${VOLUME_DRIVER}"
  rs0node2:
    driver: "${VOLUME_DRIVER}"
  rs0node3:
    driver: "${VOLUME_DRIVER}"
networks:
  mongo-network:
services:
  rs0node1:
    image: xingjiudong/mongo:${MONGO_VERSION}
    restart: unless-stopped 
    logging:
      driver: "journald"
    ports:
      - "27017"
    networks:
      - mongo-network
    volumes:
      - rs0node1:/data/db
    environment:
       constraint:node: =debian_docker07
       constraint:volume.driver: =${VOLUME_DRIVER}
       ETCD_CLIENT_IP: ${ETCD_CLIENT_IP:-127.0.0.1}
       CLUSTER_PATH: ${CLUSTER_PATH:-/mongo-config}
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
       REPLSET_NAME: ${REPLSET_NAME}
  rs0node2:
    image: xingjiudong/mongo:${MONGO_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald" 
    ports:
      - "27017"
    networks:
      - mongo-network
    volumes:
      - rs0node2:/data/db
    environment:
       constraint:volume.driver: =${VOLUME_DRIVER}
       ETCD_CLIENT_IP: ${ETCD_CLIENT_IP:-127.0.0.1}
       CLUSTER_PATH: ${CLUSTER_PATH:-/mongo-config}
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
       REPLSET_NAME: ${REPLSET_NAME}
  rs0node3:
    image: xingjiudong/mongo:${MONGO_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald" 
    ports:
      - "27017"
    networks:
      - mongo-network
    volumes:
      - rs0node3:/data/db
    environment:
       constraint:volume.driver: =${VOLUME_DRIVER}
       ETCD_CLIENT_IP: ${ETCD_CLIENT_IP:-127.0.0.1}
       CLUSTER_PATH: ${CLUSTER_PATH:-/mongo-config}
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
       REPLSET_NAME: ${REPLSET_NAME}
  haproxy00:
    image: xingjiudong/haproxy
    restart: unless-stopped
#    logging:
#      driver: "journald"
    networks:
     - mongo-network
    ports:
     - "27017:27017"
    environment:
      constraint:node: =${HAPROXY_NODE}
      MONGO_PRIMARY: ${MONGO_PRIMARY}
