version: '2.1'

volumes:
  mongos-db:
    driver: "${VOLUME_DRIVER}"
  mongos-config:
    driver: "${VOLUME_DRIVER}"
networks:
  mongos-network:
services:
  mongos:
    image: mongo:${MONGO_VERSION}
    restart: unless-stopped 
    cpu_quota: 90000
    mem_limit: 3000M
    memswap_limit: -1
    logging:
      driver: "journald"
    dns:
      - ${DNS_SERVER}
    ports:
      - "27017"
    networks:
      - mongos-network
    volumes:
      - mongos-db:/data/db
      - mongos-config:/data/configdb
    environment:
      - affinity:container!=*mongo*
      - constraint:volume.driver==${VOLUME_DRIVER}
    command: --auth 
  mongos-haproxy:
    image: openfrontier/haproxy-etcd:${HAPROXY_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    networks:
     - mongos-network
    ports:
     - "27017:27017"
     - "8000:8000"
    depends_on:
     - "mongos"
    environment:
     - constraint:node==${HAPROXY_NODE}
     - ETCD_CLIENT_IP=${ETCD_CLIENT_IP}
     - PROJECT_NAME=${PROJECT_NAME}
     - TIMEOUT_CONNECT=${TIMEOUT_CONNECT}
     - TIMEOUT_CLIENT=${TIMEOUT_CLIENT}
     - TIMEOUT_SERVER=${TIMEOUT_SERVER}
     - MAXCONN=${MAXCONN}
