version: '2.1'

volumes:
  rs0node1db:
    driver: "${VOLUME_DRIVER}"
  rs0node1configdb:
    driver: "${VOLUME_DRIVER}"
  rs0node2db:
    driver: "${VOLUME_DRIVER}"
  rs0node2configdb:
    driver: "${VOLUME_DRIVER}"
  rs0node3db:
    driver: "${VOLUME_DRIVER}"
  rs0node3configdb:
    driver: "${VOLUME_DRIVER}"
networks:
  mongo-network:
services:
  rs0node1:
    image: xingjiudong/mongo:${MONGO_VERSION}
    restart: unless-stopped 
    logging:
      driver: "journald"
    dns:
      - ${DNS_SERVER}
    ports:
      - "27017"
    networks:
      - mongo-network
    volumes:
      - rs0node1db:/data/db
      - rs0node1configdb:/data/configdb
    environment:
       constraint:volume.driver: =${VOLUME_DRIVER}
       ETCD_CLIENT_IP: ${ETCD_CLIENT_IP}
       REPLSET_NAME: ${REPLSET_NAME}
    command:  --replSet ${REPLSET_NAME} --keyFile /mongodb-keyfile
  rs0node2:
    image: xingjiudong/mongo:${MONGO_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald" 
    dns:
      - ${DNS_SERVER}
    ports:
      - "27017"
    networks:
      - mongo-network
    volumes:
      - rs0node2db:/data/db
      - rs0node2configdb:/data/configdb
    environment:
       constraint:volume.driver: =${VOLUME_DRIVER}
       ETCD_CLIENT_IP: ${ETCD_CLIENT_IP}
       REPLSET_NAME: ${REPLSET_NAME}
    command: --replSet ${REPLSET_NAME} --keyFile /mongodb-keyfile 
  rs0node3:
    image: xingjiudong/mongo:${MONGO_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald" 
    dns:
      - ${DNS_SERVER}
    ports:
      - "27017"
    networks:
      - mongo-network
    volumes:
      - rs0node3db:/data/db
      - rs0node3configdb:/data/configdb
    environment:
       constraint:volume.driver: =${VOLUME_DRIVER}
       ETCD_CLIENT_IP: ${ETCD_CLIENT_IP}
       REPLSET_NAME: ${REPLSET_NAME}
    command: --replSet ${REPLSET_NAME} --keyFile /mongodb-keyfile
  haproxy00:
    image: xingjiudong/haproxy-etcd:${HAPROXY_VERSION}
    restart: unless-stopped
    logging:
      driver: "journald"
    networks:
     - mongo-network
    ports:
     - "27017:27017"
    depends_on:
     - "rs0node1"
     - "rs0node2"
     - "rs0node3"
    environment:
      constraint:node: =${HAPROXY_NODE}
      ETCD_CLIENT_IP: ${ETCD_CLIENT_IP}
      PROJECT_NAME: ${PROJECT_NAME}
